{
 "title": "Rancher",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "containergroup", "label": "Container Group", "query": "label_values(container_group)" },
   {
    "name": "server",
    "label": "Node",
    "query": "label_values(node_boot_time, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(time() - node_boot_time{instance=~\"$server:.*\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(node_boot_time)" }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\"}[30s]))"
    }
   ]
  },
  {
   "title": "CPU aggregated",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max(100 - (avg by (cpu, instance) (irate(node_cpu{mode=\"idle\"}[30s])) * 100))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Memory aggregated",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max (100 * (node_memory_MemTotal - node_memory_MemAvailable) / node_memory_MemTotal)",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "Disk aggregated",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max (100 * (node_filesystem_size{fstype=~\"ext4\"} - node_filesystem_free{fstype=~\"ext4\"} )/ node_filesystem_size{fstype=~\"ext4\"})",
     "legendFormat": "Disk usage"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU ${server}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "repeat": "server",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu{mode=\"idle\", instance=~\"$server:.*\"}[30s])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU ${server}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu{mode=\"idle\", instance=~\"$server:.*\"}[30s])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU ${server}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu{mode=\"idle\", instance=~\"$server:.*\"}[30s])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU ${server}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu{mode=\"idle\", instance=~\"$server:.*\"}[30s])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Memory ${server}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "repeat": "server",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal{instance=~\"$server:.*\"} - node_memory_MemAvailable{instance=~\"$server:.*\"}) / node_memory_MemTotal{instance=~\"$server:.*\"}",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "Memory ${server}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal{instance=~\"$server:.*\"} - node_memory_MemAvailable{instance=~\"$server:.*\"}) / node_memory_MemTotal{instance=~\"$server:.*\"}",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "Memory ${server}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal{instance=~\"$server:.*\"} - node_memory_MemAvailable{instance=~\"$server:.*\"}) / node_memory_MemTotal{instance=~\"$server:.*\"}",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "Memory ${server}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal{instance=~\"$server:.*\"} - node_memory_MemAvailable{instance=~\"$server:.*\"}) / node_memory_MemTotal{instance=~\"$server:.*\"}",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "Disk ${server}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "repeat": "server",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max (100 * (node_filesystem_size{fstype=~\"ext4\",instance=~\"$server:.*\"} - node_filesystem_free{fstype=~\"ext4\",instance=~\"$server:.*\"} )/ node_filesystem_size{fstype=~\"ext4\",instance=~\"$server:.*\"})",
     "legendFormat": "Disk usage"
    }
   ]
  },
  {
   "title": "Disk ${server}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max (100 * (node_filesystem_size{fstype=~\"ext4\",instance=~\"$server:.*\"} - node_filesystem_free{fstype=~\"ext4\",instance=~\"$server:.*\"} )/ node_filesystem_size{fstype=~\"ext4\",instance=~\"$server:.*\"})",
     "legendFormat": "Disk usage"
    }
   ]
  },
  {
   "title": "Disk ${server}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max (100 * (node_filesystem_size{fstype=~\"ext4\",instance=~\"$server:.*\"} - node_filesystem_free{fstype=~\"ext4\",instance=~\"$server:.*\"} )/ node_filesystem_size{fstype=~\"ext4\",instance=~\"$server:.*\"})",
     "legendFormat": "Disk usage"
    }
   ]
  },
  {
   "title": "Disk ${server}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max (100 * (node_filesystem_size{fstype=~\"ext4\",instance=~\"$server:.*\"} - node_filesystem_free{fstype=~\"ext4\",instance=~\"$server:.*\"} )/ node_filesystem_size{fstype=~\"ext4\",instance=~\"$server:.*\"})",
     "legendFormat": "Disk usage"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "CPU per Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[30s])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory per Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}