apiVersion: v1
kind: Service
metadata:
  namespace: traefik
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      nodePort: 31643
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      nodePort: 30779
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: LoadBalancer
