apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: traefik
  name: traefik
  namespace: traefik
spec:
  serviceName: traefik
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traefik
    spec:
      containers:
        - args:
            - --ping
            - --api.dashboard
            - --api.insecure=false
            - --entrypoints.http.Address=:80
            - --entrypoints.https.Address=:443
            - --providers.kubernetesingress
            - --providers.kubernetescrd
            - --certificatesResolvers.letsencrypt.acme.storage=/acme/acme.json
            - --certificatesResolvers.letsencrypt.acme.email=romain.vernoux@zenika.com
            - --certificatesResolvers.letsencrypt.acme.dnsChallenge.provider=gcloud
            - --certificatesResolvers.letsencrypt-tls.acme.storage=/acme/acme-tls.json
            - --certificatesResolvers.letsencrypt-tls.acme.email=romain.vernoux@zenika.com
            - --certificatesResolvers.letsencrypt-tls.acme.tlschallenge=true
          env:
            - name: GCE_PROJECT
              value: zenika-labs
            - name: GCE_DOMAIN
              value: zenikalabs.com
            - name: GCE_SERVICE_ACCOUNT_FILE
              value: /service-account/traefik-service-account.json
          image: traefik:v2.8.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: traefik
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - mountPath: /acme
              name: acme
            - mountPath: /service-account
              name: traefik-service-account
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: traefik-ingress-controller
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 30
      volumes:
        - name: traefik-service-account
          secret:
            defaultMode: 420
            secretName: traefik-service-account
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        name: acme
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
