apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: traefik
  name: acme-traefik
  labels:
    app.kubernetes.io/name: traefik
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
